### ISSUE TITLE
Improve documentation for sqlInterpolate()

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#100]
- [x] dbQuoteString()
- [x] dbQuoteIdentifier()
- [x] sqlInterpolate()

https://github.com/rstats-db/DBI/issues/99#issuecomment-215369496

**Comment by aschmu** [comment]
I'm upvoting this as I'd like to use the odbc package with parametrized queries but I can't figure out how to use sqlInterpolate. I've tried all sorts of combinations with dbQuoteString and dbQuoteIdentifier en sqlInterpolate but nothing doing so far.
My issue is some parameters need to be have single quotes surrounding them (like dates) others not, in the same query. Even though the sql generated by sqlInterpolate may look ok, it can produce strange results when used in dbGetQuery.
