### ISSUE TITLE
Feature request: implement timeouts for queries

### ISSUE THREAD

**Issue by bborgesr** [r-dbi/DBI#123]
I realize this is a long, long way down the road, but wanted to leave the note here anyway. It would be nice to be able to specify for how long a connection should attempt to query the database, before throwing an error... (Or how long to try to create a new connection.)

**Comment by krlmlr** [comment]
Sure, we can add a `timeout` argument to the relevant functions to the specification.

**Comment by Aylr** [comment]
This would be very useful rather than hanging indefinitely. Which functions would need this argument?

**Comment by krlmlr** [comment]
Essentially a duplicate of #69. First we need to make sure that blocking code is interruptible and repeatable.
