### ISSUE TITLE
ODBC support for DBI

### ISSUE THREAD

**Issue by jimhester** [r-dbi/DBI#14]
I would like to add dplyr sources for generic ODBC sql connector, but in order to do that it first needs to have a DBI connector.

It seems as if one time there was support for the ODBC driver in DBI, in fact the documentation still mentions ODBC support in multiple places.

**Comment by The-Dub** [comment]
Hi, 
Sorry if the question is dumb, but I'm a little confused. 
In several places, it is  specified that `DBI `can interact with ODBC, but 
1. I can't seem to make it work with RODBC
2. There is no documentation anywhere on that
3. @hadley says a newcomer shouldn't expect it to work, but it's a 2 years old 

I've been programming in R & Shiny for a while, using `RODBC`, and it's working fine, but I am thinking it's time to update to a relational DB interface, and `DBI` seems to be great at that. (plus it has a lot of handy function, like `sqlInterpolate`  that would make my life easier...)

Anyway, just looking for a confirmation or a direction!
Thank you.

**Comment by jimhester** [comment]
https://github.com/teramonagi/RODBCDBI is a package that wraps RODB in a ODBC wrapper.

**Comment by The-Dub** [comment]
Thanks,
I was looking into that but was wondering if there was a more native way of doing it instead of going through another layer.
