### ISSUE TITLE
Dynamically list methods in generic documentation

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBI#162]
This will require a `\Sexpr{}` tag that calls an internal function that generates Rd

Sketch of needed code:

```R
library(DBI)
library(RSQLite)
library(RMySQL)
library(RPostgreSQL)

methods <- methods::findMethods("dbConnect")

# Extracted from roxygen2::object_topic.s4method
s4_topic <- function(x) {
  sig <- paste0(x@defined, collapse = ",")
  paste0(x@generic, ",", sig, "-method")
}

sapply(methods@.Data, s4_topic)
```

**Comment by krlmlr** [comment]
The `\Sexpr{}` seem to be rendered at install time, tested with `\Sexpr{runif(1)}`. Unless I'm missing something, a fully dynamic inline list cannot be implemented reliably.

Instead, I suggest to add an alias of the form `dbConnect-impl` to the documentation of each method in all DBI backends, and link to that. This seems close to the intent of this issue. Please advise.

**Comment by hadley** [comment]
You need `[stage=render]`: https://cran.rstudio.com/doc/manuals/r-devel/R-exts.html#Dynamic-pages

**Comment by krlmlr** [comment]
Thanks, works. Thinking about using `@template` and `@templateVar` to reduce redundancy, will these tags stay around?

**Comment by hadley** [comment]
They will, but `@evalRd` in dev roxygen is a little nicer (dev roxygen CRAN submission is blocked by callr which is blocked by processx)
