### ISSUE TITLE
Ensure all backends have a format method?

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBI#163]
That provides a brief summary suitable for description the connection in messages to the user

**Comment by krlmlr** [comment]
How is this different from `show()`? How many lines/characters should that summary be?

**Comment by hadley** [comment]
It would return a value, rather than `print()`ing. The default `show()` method could just `print()` the default `format()` method. 

I was think it would be a single line.

**Comment by krlmlr** [comment]
Done, `format()` returns a single-line string for now.
