### ISSUE TITLE
SQL class should not inherit from character

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#164]
- To avoid ambiguity with S4 method dispatch
- `[` and `[[` currently coerce to character, should return SQL object instead

@hadley: Do you remember why you made SQL inherit from character?

```
setClass("SQL", contains = "character")
```

**Comment by hadley** [comment]
Because it is a character vector? As long as it has an as.character method I don't think this change should break anything.

**Comment by krlmlr** [comment]
Tried it, but it's not worth the effort.
