### ISSUE TITLE
sqlInterpolate zero-length variable

### ISSUE THREAD

**Issue by hannesmuehleisen** [r-dbi/DBI#167]
Currently, sqlInterpolate requires variables to have at least one character after the ?. But a common use case is also to use a single `?` and positional parameters to fill a query. Any political reason `sqlInterpolate` could not be extended to support this?

**Comment by krlmlr** [comment]
I don't see any, would you like to contribute?

Can DBI standardize on a single syntax for placeholders (#52)? This means that for DBMS that support other syntaxes, `sqlInterpolate()` would transform the DBI syntax to the DBMS syntax.

**Comment by hannesmuehleisen** [comment]
I like the positional "?" and named ":" proposal and could send a PR. Should I? We could then also add generic support for parameter filling to `dbExecute` and friends.

**Comment by krlmlr** [comment]
Thanks. I think this is a good way forward. Happy to review a PR.

**Comment by krlmlr** [comment]
Could we look at two very minor issues in sqlParseVariables() along the way?

- Use numeric instead of character indexes (https://github.com/rstats-db/DBI/pull/83#discussion-diff-54754319)
- Carefully use integers to avoid coercion (https://github.com/rstats-db/DBI/pull/83#discussion-diff-54754528)

**Comment by hannesmuehleisen** [comment]
Certainly will have a look. Expect to send PR within a week.

**Comment by hannesmuehleisen** [comment]
Also, what should happen if a `?` is followed by an alphanumeric string? Error/warning/ignore? Similarly, what if a `:` has no name? assume positional variable (with warning?) or error?

**Comment by krlmlr** [comment]
I'm fine with errors in both cases, even SQLite3 doesn't accept this syntax: https://www.sqlite.org/c3ref/bind_parameter_name.html. But RSQLite does support `?1`, `?2` etc..

Generally, our syntax should be translatable to that of the target DBMS if it supports placeholders. With a bit of work we could translate named placeholders to anonymous placeholders (by reordering and repeating if necessary). From that perspective, I think we're fine with supporting anonymous `?` and named `:` only.

**Comment by krlmlr** [comment]
@hannesmuehleisen: Are you still interested in improving `sqlInterpolate()`?

**Comment by hannesmuehleisen** [comment]
yes!

**Comment by hannesmuehleisen** [comment]
On second thought, is it wise to break existing code by switching the named variable syntax from `?asdf` to `:asdf`? Alternative would be to simply allow empty `?` variables.

**Comment by krlmlr** [comment]
Thanks. I have found calls to `sqlInterpolate()` in at least two CRAN packages, we probably want to stick with the old syntax and allow empty `?` variables as you suggested.

In this case we definitely don't want to mix named and unnamed vars or placeholders, throwing an error is fine.

**Comment by hannesmuehleisen** [comment]
I have changed the PR. In addition, it now also enforces positional variables being passed as nameless arguments. Hope thats ok.

**Comment by krlmlr** [comment]
Absolutely. Thanks a lot!

**Comment by krlmlr** [comment]
Closed by #216.
