### ISSUE TITLE
Colliding representations of -2³¹ and NA_INTEGER

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#168]
DBMS can usually represent both -2³¹ and NULL, because they use a separate bit for nullness. R can't:

``` r
library(DBI)
dbGetQuery(dbConnect(RSQLite::SQLite()), paste0("SELECT ", -2^31))
#>   -2147483648
#> 1          NA
```

I think backends should raise a warning here, similarly for the similar 64-bit scenario, or perhaps for strings with embedded NUL characters (#94). @hadley @hannesmuehleisen @gaborcsardi: What do you think?

**Comment by hannesmuehleisen** [comment]
MonetDB[Lite] uses the same NULL representation as R. So thats quite convenient...

**Comment by krlmlr** [comment]
Silently returning `NA` is consistent with the behavior for `+-Inf` and `NaN` for numerics, no need to change anything here right now.
