### ISSUE TITLE
dbQuoteLiteral

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBI#172]
Needs to convert:

* integers
* doubles (adding trailing .0, and handling Inf, -Inf)
* logical
* dates
* date/times
* strings 
* SQL strings

All need to convert NA to NULL.

Could replace `dbQuoteString()`

**Comment by hannesmuehleisen** [comment]
perhaps also `raw`/`BLOB`?

**Comment by krlmlr** [comment]
Should also preserve names (#173).

**Comment by krlmlr** [comment]
@hannesmuehleisen: Is the `X'xxxx'` syntax for BLOB literals sufficiently standardized to warrant inclusion in DBI?

```r
    if (is.list(x)) {
      is_blob <- vapply(x, function(x) is.raw(x) || is.null(x), logical(1))
      if (!all(is_blob)) {
        stop("Lists must contain raw vectors or NULL", call. = FALSE)
      }

      blob_data <- vapply(x, function(x) paste(format(x), collapse = ""), character(1))
      if (length(blob_data) == 0) return(SQL(character()))
      else return(SQL(paste0("X'", blob_data, "'")))
    }
```

**Comment by hannesmuehleisen** [comment]
The `X` is standardized (ISO/IEC 9075-2:2008(E)) at least in SQL 2008 which I have here. It also says both upper- and lowercase is ok.
![screen shot 2017-11-09 at 16 27 27](https://user-images.githubusercontent.com/227792/32613335-f0147f3a-c56a-11e7-8d85-c8fcf6d24c0e.png)

**Comment by krlmlr** [comment]
Thanks!

**Comment by hadley** [comment]
FWIW I think SQL 2003 support is still kind of shaky, so it's quite possible that many databases won't support this. (But it's still fine to have in DBI)
