### ISSUE TITLE
dbQuoteIdentifier inconsistency

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBI#175]
The documentation has:

> dbQuoteIdentifier() returns an object that can be coerced to character, of the same length as the input. 

But in a bigrquery DBItest I'm seeing

```
4. Failure: DBItest: SQL: quote_identifier_not_vectorized ----------------------
length(letters_out) not equal to 1.
1/1 mismatches
[1] 3 - 1 == 2
```

**Comment by krlmlr** [comment]
Are you running the CRAN version of DBItest by any chance? In the dev version, I'm seeing the correct test: https://github.com/rstats-db/DBItest/blob/be3fce5100f2e23cc9cd7f6a3944c251729347a5/R/spec-sql-quote-identifier.R#L23

**Comment by hadley** [comment]
Yeah, the CRAN version.

**Comment by krlmlr** [comment]
We now have a `quote_identifier_vectorized` test.
