### ISSUE TITLE
Should dbFetch on a result with zero rows still return a data frame with the right columns?

### ISSUE THREAD

**Issue by alexfun** [r-dbi/DBI#178]
PostgreSQL table:

```
create table dplyr_test (
id serial primary key
);
insert into dplyr_test (id)  SELECT generate_series(1,1000);
```
R code to create result set: `tmp <- postgresqlExecStatement(db$con, "select * from dplyr_test where id = -1")`

However, when fetching the zero results with dbFetch, I obtain:

> dbFetch(tmp)
data frame with 0 columns and 0 rows

Whereas if I run the select sql command against the database directly I get a zero row, one column output.

Unless I am reading the helpfile wrong, I don't think this behaviour is compatible with:

> dbFetch() always returns a data.frame with as many rows as records were fetched and as many
columns as fields in the result set, even if the result is a single value or has one or zero rows.

session info:
`
[1] data.table_1.10.0 dplyr_0.5.0       RPostgreSQL_0.4-1 DBI_0.6-1  `

**Comment by krlmlr** [comment]
DBI cannot enforce this, just test for it. I'll be working on making the RPostgres package DBI-compliant over the next months.

**Comment by alexfun** [comment]
Thanks for your reply. Does this mean this feature is compliant at the package level and RPostgreSQL is not compatible with it?

**Comment by krlmlr** [comment]
This seems that way at the moment.
