### ISSUE TITLE
support for UUID/GUID?

### ISSUE THREAD

**Issue by r2evans** [r-dbi/DBI#179]
More of a discussion than a feature request atm ...

**Background**: SQL Server often (always?) uses GUIDs (`uniqueidentifier`) instead of integers for keys. Other DBMS support them (PostgreSQL [`UUID`](https://www.postgresql.org/docs/9.6/static/datatype-uuid.html) type; MySQL can use [`binary(16)`](http://mysqlserverteam.com/storing-uuid-values-in-mysql-tables/), though it is not standard; SQLite would likely need to use `TEXT`, perhaps inefficient).

When uploading a table with `sqlCreateTable` or similar mechanism, the target data types are auto-determined based on the R data types (via `dbDataType`). This works fine except when the intention is to convert one of the GUID `character` columns into a UUID on the server. (For reference, I'm playing with the [`uuid`](https://cran.r-project.org/web/packages/uuid/index.html) package.) One reason I'd be uploading to a table in this way with GUIDs instead of manually creating the table is a quick ["update/join"](https://stackoverflow.com/a/1293347/3358272).

```r
df <- tibble::tibble(id=sapply(1:3, function(x) uuid::UUIDgenerate()), num=1:3, txt=letters[4:6])
df
# # A tibble: 3 × 3
#                                     id   num   txt
#                                  <chr> <int> <chr>
# 1 de492d56-4bac-11e7-8f85-850fe21eb080     1     d
# 2 de492d57-4bac-11e7-8f85-850fe21eb080     2     e
# 3 de492d58-4bac-11e7-8f85-850fe21eb080     3     f
DBI::dbDataType(conn, df) # conn is a connection to 
#     id    num    txt 
# "TEXT"  "INT" "TEXT" 
```

`"TEXT"` is technically correct, obviously, but it might be improved:

1. Ideally, it could be identified as `UUID` (dbms-specific).
2. Lacking that, perhaps `CHAR(36)` (dbms-specific).

The current working method is to create the table first, overriding the default field types:

```r
DBI::sqlCreateTable(conn, "uuidtest", c(id="UUID", num="INT4", txt="VARCHAR(8)"))
<SQL> CREATE TABLE "uuidtest" (
  "id" UUID,
  "num" INT4,
  "txt" VARCHAR(8)
)
```

and then inserting the data.

First and foremost, **do you think it useful to automate/improve on this?** My supposition for asking this question is potential increased utility in using UUIDs (though my perspective is admittedly narrow). Three options if "yes":

1. Use regular expressions, ala `grepl('^[[:alnum:]]{8}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{4}-[[:alnum:]]{12}$', x)`, to infer if the field is a GUID. This feels hack-y to me and certainly prone to problems.
2. Support a `"uuid"` class, so that something like `class(df$id) <- "uuid"` would encourage `dbDataType` to correctly identify the type.
3. Introduce a new R type that provides the character representation of the actual binary data. (Note that `uuid::UUIDGenerate()` creates and returns the string representation, not a possibly more-efficient binary store.) This option has significantly more overhead since it requires many more supporting functions (comparisons, etc, in order to support actions like filtering and joins).)

"2" is by far the simplest and most straight-forward approach. Unfortunately, it's fairly fragile in that concatenation (`c`) will resort it to `"character"` class. (Other problems exist, I'm guessing.)

**Comment by stephlocke** [comment]
Guids could really do with being supported - at least to get converted into characters inbound.

**Comment by krlmlr** [comment]
Closing in favor of https://github.com/r-dbi/DBI/issues/203, which describes a more general approach to the problem.
