### ISSUE TITLE
DBI seems to lose times from PostgreSQL timestamps

### ISSUE THREAD

**Issue by jcpayne** [r-dbi/DBI#180]
I have edited this question to add a reproducible example:

I've noticed with both DBI and RPostgreSQL that when I import a large-ish PostgreSQL table into R, the times disappear from "timestamp" columns (which include both date and time).  I am using a recent Macbook Pro running Sierra 10.12.5, with R version 3.3.2 and PostgreSQL 9.4.4 (with PostGIS).  

Example:
I can create a small table (20 rows) in PostgreSQL with two columns: id (integer) and a series of hourly times ('timestamp').

`CREATE TABLE smalltable AS (
 WITH data as (
  SELECT 
	generate_series(1,20) as id,
	('2010-01-01 12:00:00'::timestamp  + interval '1 hour' * generate_series(1, 20))::timestamp as tstamp)
 SELECT id, tstamp FROM data)
`

If I fetch the table into R, using DBI (or RPostgreSQL), everything looks fine.
`res <- dbSendQuery(con, "SELECT * from smalltable")`
`smalltable<- fetch(res, n = -1)`
`head(smalltable)`
id              tstamp
1   2010-01-01 13:00:00
2   2010-01-01 14:00:00
3   2010-01-01 15:00:00
4   2010-01-01 16:00:00
5   2010-01-01 17:00:00
6   2010-01-01 18:00:00

Now I simply increase the size of the table to 10,000 rows, leaving everything else the same:
`CREATE TABLE largetable AS (  
   WITH data as (  
    SELECT 
      generate_series(1,10000) as id,
      ('2010-01-01 12:00:00'::timestamp  + interval '1 hour' * generate_series(1, 10000))::timestamp as tstamp)  
   SELECT id, tstamp FROM data)  
`

Now when we fetch it into R, the times have disappeared from the timestamp:
`res <- dbSendQuery(con, "SELECT * from largetable")`
`largetable<- fetch(res, n = -1)`
`head(largetable)`
id     tstamp
1    2010-01-01
2    2010-01-01
3    2010-01-01
4    2010-01-01
5    2010-01-01
6    2010-01-01

The times are really gone, as you can confirm by formatting them to include times:
`format(largetable[1:6,2], "%Y-%m-%d %T")`
[1] "2010-01-01 00:00:00" "2010-01-01 00:00:00" "2010-01-01 00:00:00" "2010-01-01 00:00:00"
 [5] "2010-01-01 00:00:00" "2010-01-01 00:00:00" 

The same effect happens if you call it from an RMarkdown notebook.  I don't know exactly where the cutoff for "large" is.  I've mentioned this in the RPostgreSQL community, but had no response.  It's an annoying problem since it requires a workaround (other than that, I love the capabilities of DBI and rely on it). 

Thanks.

**Comment by r2evans** [comment]
I can confirm that this does *not* happen for data type `timestamptz` ... though that may be partly because it is interpreted as a `character` instead of `POSIXct`. (Currently on R-3.3.3, DBI (rstats-db/DBI@6952b83), RPostgres (rstats-db/RPostgres@f1835d3).)

**Comment by jcpayne** [comment]
Thanks, I've edited my question to add a reproducible example.

**Comment by krlmlr** [comment]
Can you please double-check with current RPostgres, and open a new issue in the RPostgres repo if the problem persists?
