### ISSUE TITLE
dbGetQuery() function does not throw exception into Global environment

### ISSUE THREAD

**Issue by GediminasPukys** [r-dbi/DBI#183]
Hi,
when I use function dbGetQuery() with wrong SQL, error is not thrown into Global environment.
for example:
`tryCatch(dbGetQuery(conn,"select * from table_which_does_not_exists"), error=function(e){message("error is caught")}, NULL)`
i get answer 
'Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  relation "table_which_does_not_exists" does not exist
)
NULL
Warning message:
In postgresqlQuickSQL(conn, statement, ...) :
  Could not create executeselect * from table_which_does_not_exists'

Expected to get "error is caught".

I have used DBI for a whlie and previously it was working fine (throwing exceptions into Global). 
Why did behavior change and what would you recommend to solve this issue?

**Comment by krlmlr** [comment]
This is specific to the DBI backend, RPostgres should return an error as expected.
