### ISSUE TITLE
warning: In max(n) : no non-missing arguments to max; returning -Inf

### ISSUE THREAD

**Issue by randomgambit** [r-dbi/DBI#184]
Hello,

I am using this great package along with `sparklyr` to run some SQL queries on my spark cluster. 
My query is a basic one such as

```
query <- "CREATE TABLE new_df AS SELECT * FROM df WHERE u rlike '.*hello.*'"
DBI::dbGetQuery(sc, query)

```
which gives the warning

```
> DBI::dbGetQuery(sc, query)
Warning message:
In max(n) : no non-missing arguments to max; returning -Inf
```

What does that mean? I see some output though. So is the query working correctly?

Thanks!

**Comment by randomgambit** [comment]
@krlmlr any ideas? thanks!!!

**Comment by krlmlr** [comment]
Thanks, forgot to reply that a reprex would be very helpful.

Could you please try `dbExecute()`, which is the new preferred method for SQL statements that don't return a result set?

**Comment by krlmlr** [comment]
Closing, please file a new issue if the problem persists.
