### ISSUE TITLE
DBItest:::read_table_row_names_false tests for `dbReadTable(row.names=NULL)` but `DBI::readTable()` errors if `length(row.names) == 0`

### ISSUE THREAD

**Issue by jimhester** [r-dbi/DBI#185]
https://github.com/rstats-db/DBItest/blob/master/R/spec-sql-read-table.R#L55, explicitly tests for the case when `row.names = NULL`, however https://github.com/rstats-db/DBItest/blob/master/R/spec-sql-read-table.R#L55 fails if `length(row.names) != 1`, so `row.names = NULL` will fail.

As `row.names = NULL` is mentioned in the documentation it seems the DBI implementation is incorrect.

**Comment by krlmlr** [comment]
Closed in 258b967.
