### ISSUE TITLE
Think about argument to `dbRemoveTable()` that drops only if the table exists

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#197]
Useful for `dbWriteTable()` or for manually implementing it (#74).

Naming suggestion: `dbRemoveTable(safe = TRUE)`

**Comment by hadley** [comment]
I think the right argument is `force = TRUE` so following the convention `rm`

**Comment by krlmlr** [comment]
I've decided in favor of `fail_if_missing = TRUE`, because `--force` in `rm` implies more than just "skip if missing".
