### ISSUE TITLE
sqlAppendTable has issues with date time fields

### ISSUE THREAD

**Issue by ethankale** [r-dbi/DBI#204]
If you try to use the SQL generated by `sqlAppendTable()`, and your data includes a date/time column, the generated SQL will not work (at least on MS SQL).  The issue seems to be that the dates are printed out as characters, and POSIXct fields are printed as %Y-%m-%d %H:%M:%S.  The SQL parser fails on the space between day and hour.  A fix is to use format to add single quotes in the data frame or tibble:

    format(dt, format = "'%Y-%m-%d %H:%M:%S'")

I have not tried this with other databases; maybe it works in MySQL/Postgres/SQLite?

**Comment by krlmlr** [comment]
Thanks. We still need to review the responsibilities of the `sql...()` interfaces, but maybe the new `dbQuoteLiteral()` can help here.

**Comment by HarlanH** [comment]
This is definitely a problem with Redshift/Postgres. And maybe not just dates -- even text columns I'm having to manually quote before uploading the table.

**Comment by avsdev-cw** [comment]
Just encountered this myself on a 10M row database - is there any discussion to a resolution for this?

**Comment by krlmlr** [comment]
We now have `dbQuoteLiteral()`, perhaps we can pass a data frame where each column has been processed by that method to `sqlAppendTable()` ?

**Comment by avsdev-cw** [comment]
That or the capability to pass in a TRUE/FALSE vector of ncol length indicating which columns to escape.  

In some instances (it escapes my memory which ones at the moment) dbQuoteLiteral doesn't behave in the way it should with regards to how it escapes some columns - I ended up cherry-picking columns to escape because of this.

If the latter is solved then the former is no longer needed - I'll try and remember the instances when I get a chance

**Comment by krlmlr** [comment]
Does the new `dbAppendTable()` help? It uses binding and prepared statements instead of `dbQuoteIdentifier()`.

If you happen to find an instance where `dbQuoteLiteral()` produces invalid SQL I'd be happy to see it.

**Comment by adampdavis** [comment]
`dbAppendTable()` seems to be having some trouble (at least on my Postgres/Redshift connection). Even with a simple table:
```
src <- dplyr::src_postgres(my_infos)
my_df <- data.frame(x = 1:2, y = c('a', 'b'))
DBI::dbCreateTable(src$con, 'test', my_df) # works fine, empty table in Redshift
DBI::dbAppendTable(src$con, 'test', my_df)
```
throws
```
Error in postgresqlExecStatement(conn, statement, ...) : 
  RS-DBI driver: (could not Retrieve the result : ERROR:  syntax error at or near ","
LINE 4:   (?, ?)
```

Re: original topic with timestamps, but for Postgres/Redshift. I have had success with explicit typecasting and manual quoting, borrowing a little bit of the original solution supplied.
```
# pretend my_df now has timestamp
my_df <- dplyr::mutate_if(my_df,
                          sapply(my_df, inherits, 'POSIXct'), # make changes to all dttm
                          dplyr::funs(DBI::SQL(format(., format = "'%Y-%m-%d %H:%M:%S +00'::timestamp"))))
query <- DBI::sqlAppendTable(upst_rs$con, 'test', my_df, row.names = NA)
DBI::dbExecute(upst_rs$con, query)
```
delivers what I was looking for.

**Comment by krlmlr** [comment]
Thanks. What does `dbQuoteLiteral()` produce for your timestamp values? Can you use `sqlAppendTable()` with a data frame where all columns have been processed with `dbQuoteLiteral()`?

Do prepared queries work at all with Redshift?
