### ISSUE TITLE
CRAN Vignette Link Not found?

### ISSUE THREAD

**Issue by pgensler** [r-dbi/DBI#210]
Seems like the URL: http://rstats-db.github.io/DBI from https://cran.r-project.org/web/packages/DBI/DBI.pdf is broken. Most likely a simple fix to this site:
http://r-dbi.github.io/DBI/ ??

**Comment by krlmlr** [comment]
Thanks, this is already fixed in the development version. We need to submit to CRAN so that they can pick it up. Unfortunately, GitHub doesn't implement a redirect for its GitHub Pages when an organization is renamed.
