### ISSUE TITLE
How to Integrate ${} SQL placeholder to Rmarkdown chunk

### ISSUE THREAD

**Issue by harryprince** [r-dbi/DBI#217]
I am writing Spark SQL by sparklyr in Rnotebook

```{r}
year = "2018-01-09"
````

```{sql connection=sc}
select * from tbl_name where partition = ${year}
```

it seems ${} language sugar does not work

**Comment by krlmlr** [comment]
Thanks. Could you please file an issue in the sparklyr repo? https://github.com/rstudio/sparklyr/
