### ISSUE TITLE
Allowing the user to specify enclosing collections via `dbQuoteIdentifier`

### ISSUE THREAD

**Issue by Adam-Hoelscher** [r-dbi/DBI#222]
#### Present State
dbQuoteIdentifier quotes around the entire name given to it, disregarding square brackets.
e.g. `dbQuoteIdentifier(con, '[foo].[bar]')` returns `"\"[foo].[bar]\""`. It's then treated as one name and not a table `bar` inside a schema `foo` when passed to SQL.

#### Issue
This keeps the user from being able to specify a schema and catalog when using `sqlCreateTable`. The SQL returned always creates the table in the users default catalog and schema.
e.g. setting `table = '[foo].[bar]'` results in a SQL statement that creates a table name '[foo].[bar]' instead of a table named 'bar' in a schema named 'foo'.

#### Proposal
Enhance dbQuoteIdentifier so that square brackets are not encased in quotes, allowing the user to provide a catalog for a schema, a schema for a table, or a table for a column.

#### Alternatives
Insert a flag in `sqlCreateTable` that allows the user to not run the table name through `dbQuoteIdentifier`. This only fixes the specific use case I've sited, but I am unaware of any others (granted, I've been using the package for only about 2 days).

**Comment by krlmlr** [comment]
Thanks. Can you please take a look at #220 for an implementation sketch? You will be able to do:

```r
dbQuoteIdentifier(con, Id(schema = "schema", table = "table"))
dbReadTable(con, Id(schema = "schema", table = "table"))
...
```

I'm working on implementations of this paradigm for RSQLite, RMariaDB and RPostgres.

**Comment by Adam-Hoelscher** [comment]
Thanks for responding. I agree that the enhancements from [#220](https://github.com/r-dbi/DBI/pull/220) will solve the issue.

**Comment by krlmlr** [comment]
I forgot that you can already do it manually with `SQL()`:

```r
SQL('[foo].[bar]')
```
