### ISSUE TITLE
Oracle spatial column support

### ISSUE THREAD

**Issue by obrl-soil** [r-dbi/DBI#225]
Per the issue raised here - https://community.oracle.com/thread/4039869 

Is there anything that can/should be done at the DBI end of things to assist the ROracle team in supporting extraction of spatial data from Oracle databases?

**Comment by krlmlr** [comment]
Thanks. I think the relevant issue is #203.

@etiennebr has contributed an extension to *RPostgres*, r-dbi/RPostgres#114, that provides support for custom data types (by adding an R attribute to the data which is returned as character). A consistent solution across backends may be better but requires substantially more work.
