### ISSUE TITLE
DBI::dbExecute not returning error on maximum size

### ISSUE THREAD

**Issue by ldfreight** [r-dbi/DBI#227]
Hello, 

I am trying to send a very large "MERGE xxx AS target USING Values ..." statement on a SQL Server. 
DBI::dbExecute returns 0 indeed as no row was affected. However I cannot find any particular error message.
Is this the normal behavior? What is the best practice to know (either _a priori_ or _a posteriori_) that I should split my query in smaller chunks?

**Comment by krlmlr** [comment]
I don't know what `MERGE` does. Which DBI backend are you using? If `dbExecute()` returns without error, it means that the query should have been processed, but it's up to the backend to ensure that errors are reported correctly.
