### ISSUE TITLE
dbListObjects() documentation

### ISSUE THREAD

**Issue by RLesur** [r-dbi/DBI#237]
I don't understand the `dbListObjects` documentation for the `prefix` argument. I'm sorry if the answer is obvious.  
It is stated that:

> The `table` column is of type list. Each object in this list is suitable for use as argument in `dbQuoteIdentifier()`. 
https://github.com/r-dbi/DBItest/blob/2f59ef31d157cbbd95eaf67869e60ed03f6d035b/R/spec-sql-list-objects.R#L26

> Values in `table` column that have `is_prefix == TRUE` can be passed as the `prefix` argument to another call to `dbListObjects()`.
https://github.com/r-dbi/DBItest/blob/2f59ef31d157cbbd95eaf67869e60ed03f6d035b/R/spec-sql-list-objects.R#L134

I understand from these quotes that values passed to the `prefix` argument should be suitable for use as argument in `dbQuoteIdentifier()`.

However, the documentation for the `prefix` argument says:

> `prefix` A fully qualified path in the database's namespace, or `NULL`.  will be passed to `dbUnquoteIdentifier()`.
https://github.com/r-dbi/DBI/blob/2bcb77d03ab52c8fd14ff76af1087a8b12dcbd25/R/DBConnection.R#L388

Shall I understand that the `prefix` argument is suitable for use as argument in both `dbQuoteIdentifier()` and `dbUnquoteIdentifier()`? (I wonder how it is possible).

**Comment by krlmlr** [comment]
Thanks. The documentation could be clearer on the fact that `dbQuoteIdentifier()` returns `SQL` objects unchanged, and `dbUnquoteIdentifier()` returns `Id` objects unchanged. Calling `dbQuoteIdentifier()` on `Id` converts it to an `SQL`, calling `dbUnquoteIdentifier()` on an `SQL` converts it to an `Id` (or dies trying).

I'll tweak the documentation. Are the examples more helpful?

**Comment by krlmlr** [comment]
I'm also planning a blog post to describe the intended usage.

**Comment by RLesur** [comment]
Thanks @krlmlr for your quick answer! That's clear using `Id`.  
With your answer, I realize that I have to implement schemas as instances of the `Id` class in the result of the `dbListObjects` function.   
I thought this was forbidden because `names(dbUnquoteIdentifier(conn, dbQuoteIdentifier(conn, x))[[1]]@name)` is always equal to `"table"`.  
I think it is a little bit confusing to use the same class for both tables and schemas.

**Comment by krlmlr** [comment]
Yes, `dbListObjects()` provides a DBMS-agnostic way to generate instances of `Id`. *RPostgres* and *RMariaDB* contain working implementations that draw from `INFORMATION_SCHEMA`, you might be able to borrow from there.

**Comment by RLesur** [comment]
Thanks! I'll have a look to _RPostgres_ and _RMariaDB_.
