### ISSUE TITLE
Update documentation on how to cope with stored procedures

### ISSUE THREAD

**Issue by aryoda** [r-dbi/DBI#239]
The `dbCallProc` was set to *deprecated* (see #7) but the Vignette is still proposing it to call stored procedures, e. g:

https://github.com/r-dbi/DBI/blob/master/vignettes/DBI-1.Rmd
> dbCallProc(conn, storedProc, ...)(optional):
> : invokes a stored procedure in the DBMS and returns a DBIResult object.
> [Stored procedures are *not* part of the ANSI SQL-92 standard and
> vary substantially from one RDBMS to another.]

https://github.com/r-dbi/DBI/blob/master/vignettes/DBI-proposal.Rmd

> callProc
> : invokes a stored procedure in the RDBMS (tentative). Stored procedures are not part of the ANSI SQL-92 standard and possibly vary substantially from one RDBMS to another. For instance, Oracle seems to have a fairly decent implementation of stored procedures, but MySQL currently does not support them.
> 

1. These old parts should be removed
2. The documentation should be updated to indicate the recommended way of calling stored procedures using `DBI` (using `dbSendStatement` and `dbGetQuery`?)

See also:
https://stackoverflow.com/questions/47897042/retrieve-output-from-stored-procedure-result-in-r-with-odbc-dbi

**Comment by krlmlr** [comment]
Thanks. I agree that the vignettes need a cleanup.

For stored procedures, do you suggest to add an entry to `?dbGetQuery` and `?dbExecute` ? How are stored procedures different from "regular" queries that use `SELECT` or `INSERT`?

**Comment by aryoda** [comment]
When I saw the DBI API first I was looking for a way to call stored procedures by browsing through the function names but couldn't find a suitable function.

I am proposing to add a sentence to `?dbCallProc` to indicate the "new way" of calling stored procedures, e. g. in the `description` section:

> This function is deprecated. The recommended way of calling a stored procedure is now \code{\link{dbGetQuery}} (if a result set is returned) and \code{\link{dbExecute}} for data manipulation and other cases.

I would also add a sentence to `dbGetQuery` to clarify that it also supports stored procedures, because the first sentence of the details sections could be misunderstood:

> This method is for SELECT queries only.

Something like

> This method is for SELECT queries only (incl. other SQL statements that return a result like, e. g. execution of a stored procedure)

I think, I should have sent a pull request to minimize your work!

**Comment by krlmlr** [comment]
Thanks for looking into it, a PR would be great!

**Comment by aryoda** [comment]
My issue my PR :-)

I will update the docs (incl. the vignette if not already done) and send a PR

Please give me some time for that (not highest prio ATM)...
