### ISSUE TITLE
Broken DBI spec web site

### ISSUE THREAD

**Issue by aryoda** [r-dbi/DBI#243]
The DBI specification web site does only show a small part of the spec:

https://cran.r-project.org/web/packages/DBI/vignettes/spec.html

This link was contained in https://www.r-dbi.org/blog/dbi-1-final/

There seems to be a problem in an R chunk (which I could not reproduce when building the `spec.Rmd` using the master of `DBI`):

>  Examples
> 
> RSQLite::SQLite()
> 
> ## Error: /tmp/Rtmp4vZ7Gp/Rbuild79c727dc8df9/DBI/man/dbDataType.Rd:35: not a namespace
>

**Comment by krlmlr** [comment]
Thanks. I'm aware of the problem. I couldn't replicate it locally, and I hope this goes away with the upcoming CRAN release. Reference: #234.

**Comment by krlmlr** [comment]
For now a rendered version is on http://dbi.r-dbi.org/articles/spec.
