### ISSUE TITLE
dbAppendTable doesn't work

### ISSUE THREAD

**Issue by blmayer** [r-dbi/DBI#245]
I am connected with a MySQL database with "mySchema.myTable" already there and when I execute the command:

` > dbAppendTable(conn, "mySchema.myTable", myValues)
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for INSERT INTO "mySchema.myTable"`

Then it prints my column names and

`In addition: Warning message:
In if (is.na(v)) { :
  the condition has length > 1 and only the first element will be used`

Can someone help me?

Thanks

**Comment by krlmlr** [comment]
Thanks. Could you please post a more complete example? How does your `dbConnect()` call look like?
