### ISSUE TITLE
dbReadTable does not pass arguments on

### ISSUE THREAD

**Issue by hannesmuehleisen** [r-dbi/DBI#248]
dbReadTable takes ... arguments but does not pass those on to dbSendQuery. Is this intentional?

**Comment by krlmlr** [comment]
Thanks. Current `dbReadTable()` passes the dots only to `dbQuoteIdentifier()`, not to `dbGetQuery()` . They aren't used in `dbQuoteIdentifier()`, but why would we want them in `dbGetQuery()` ?

It seems interesting to explicitly support the `n` argument, though.

**Comment by krlmlr** [comment]
Closing as duplicate of #240.
