### ISSUE TITLE
partial argument match in dbAppendTable

### ISSUE THREAD

**Issue by MikeBadescu** [r-dbi/DBI#249]
On line 151 in `table-insert.R`, the name of the argument should be `params` not `param` - (dbSendQuery expects `param`)
https://github.com/r-dbi/DBI/blob/40a7de446cf0ca9d3e61e0c3890d5fb3047d72f7/R/table-insert.R#L151

I believe a similar issue affects RPostgres
https://github.com/r-dbi/RPostgres/blob/7fe22ca9e887ad73f45c9ae3c77991e3725a5c71/R/tables.R#L203

(I discovered this issue while using package `strict`)

**Comment by krlmlr** [comment]
Closed in #246.
