### ISSUE TITLE
dbSendQuery for signature "Microsoft SQL Server", "missing."

### ISSUE THREAD

**Issue by ankushreddy** [r-dbi/DBI#251]
Hi All,

i am trying to connect to a sql server and pull the data to the web application.

Please find the code that I am using.

    library(shiny)
    library(DBI)
    library(odbc)
    serverfun<-function(input, output){
     myData <- reactive({
    con <- dbConnect(odbc::odbc(),
                          Driver = "SQL Server",
                          Server = "server",
                          Database = "dbname",
                          UID = "user",
                          #PWD = rstudioapi::askForPassword("Database password"),
                          PWD = "password",
                          Port = 1433)
    qr <- paste( "SELECT * FROM table g WHERE CategoryID = ",input$myId)
    res <- DBI::dbSendQuery(conn = con,query = qr) 
    res
    })
  
    output$tbTable <- renderTable({
    if(is.null(myData())){return ()}
    myData()
    })
    }

ui.R

    library("shiny")
     shinyUI(
  
    pageWithSidebar(
    
    headerPanel("Hide Side Bar example"),
    sidebarPanel(
      textInput("Id", "Enter ID below","1727")
    ),
    mainPanel(
      tabsetPanel(
        tabPanel("Data", tableOutput("tbTable"))
      )
    )
     )
    )

but I am getting an error saying.

Warning: Error in <Anonymous>: unable to find an inherited method for function ‘dbSendQuery’ for signature ‘"Microsoft SQL Server", "missing"’

Thank you for your help.

**Comment by ankushreddy** [comment]
@krlmlr  hi can you please take a look at this issue ant let me know if we can resolve that one.

Thanks,
Ankush Reddy.

**Comment by jimhester** [comment]
The second argument to `dbSendQuery()` is `statement`, not `query`.

change your code to

```r
res <- DBI::dbSendQuery(conn = con, statement = qr)
```

and it should be fixed.

**Comment by ankushreddy** [comment]
when I use statement then it is giving me an error saying.

Error: <SQL> 'SELECT * FROM Agile_promo'
  nanodbc/nanodbc.cpp:1587: 42S02: [Microsoft][ODBC SQL Server Driver][SQL Server]Invalid object name 'Agile_promo'. agile_promo which is 'table' in the code.

**Comment by ankushreddy** [comment]
I think I found the issue for dbListFields. we don't have to specify the schema.
but for querying we need to specify the schema.

Thanks,
Ankush Reddy.
