### ISSUE TITLE
dbReadTable/dbWriteTable not working 

### ISSUE THREAD

**Issue by aishwaryamohanakrishnan** [r-dbi/DBI#254]
Hi,

I am trying to read and write into a SQL Server. I'm able to access the table with manually creating the queries and send it to the SQL Server through the dbExecute function. But when I use the dbWriteTable or dbReadTable it throws the following errors.

> df_impm <- data.frame("primary_key"= 'IMPM_07-10-2018' ,"algo_name" = "IMPM", "sys_run_dt" = '2018-07-10 12:00:00.0000000 +00:00')
> DBI::dbExistsTable(sql_conn, 'impm')
[1] TRUE
> DBI::dbReadTable(sql_conn, 'impm')
Error in .verify.JDBC.result(r, "Unable to retrieve JDBC result set for ",  : 
  Unable to retrieve JDBC result set for SELECT * FROM "impm" (Invalid object name 'impm'.)
> DBI::dbWriteTable(sql_conn, 'impm', df_impm, row.names = F, append = T, overwrite = F)
Error in .local(conn, statement, ...) : 
  execute JDBC update query failed in dbSendUpdate (Invalid object name 'impm'.)

I've tried all resources possible, i'm not able to find a solution. It would be great if someone could help out.

Thanks,
Aishwarya

**Comment by krlmlr** [comment]
Thanks. This does look like a _JDBC_/connectivity issue. I don't understand the inconsistency between `dbExistsTable()` and `dbReadTable()`. What database are you connecting to? Would you mind trying the _odbc_ package?
