### ISSUE TITLE
Use Volatile keyword for teradata connection

### ISSUE THREAD

**Issue by kmace** [r-dbi/DBI#256]
When using Teradata, one needs to use the `VOLATILE` keyword instead of `TEMPORARY` to create a temporary table. Would it be possible to specify that here?

https://github.com/r-dbi/DBI/blob/40a7de446cf0ca9d3e61e0c3890d5fb3047d72f7/R/table-create.R#L61

**Comment by krlmlr** [comment]
Thanks. Which package do you use to connect to Teradata? How does your `dbConnect()` call look like?
