### ISSUE TITLE
sqlInterpolate not working with IN

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/DBI#259]
The following interpolation does not seem to be supported currently:

```r
sqlInterpolate(con, "select * from table where name in ?names", names = c("name1", "name2"))
```

which is supposed to be translated into

```sql
select * from table where name in ('name1','name2')
```

**Comment by krlmlr** [comment]
You still can use `SQL()`:

``` r
library(DBI)
sqlInterpolate(
  ANSI(),
  "select * from table where name in ?names",
  names = SQL("('a', 'b')")
)
#> <SQL> select * from table where name in ('a', 'b')
```

<sup>Created on 2018-10-01 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

Would you like to add documentation and/or a test?

**Comment by renkun-ken** [comment]
@krlmlr Thanks! I file an PR to add documentation and a test for this.
