### ISSUE TITLE
Overload +-Operator for Character vectors Marked as SQL?

### ISSUE THREAD

**Issue by petermeissner** [r-dbi/DBI#260]
**The Problem**

Writing SQL is a lot of pasting-together strings. The SQL() function provides a nice entry point to mark character vectors as SQL (which will result in nicer printing). 

If we have a way to mark text as SQL would it not be nice to be able to do something 'simply' put together parts of an SQL-statement in an easy manner? 

---

**The Solution**

SQL() in combination with overloading the plus operator might bring a lot of productivity gain here. 

```r
#' +-Operator for SQL
#' 
#' Pastes together two character vectors marked as SQL (via \code{SQL()}). 
#' 
#' @param a first part of SQL statement
#' @param b second part of SQL statement
#'
#' @export
#' @examples
#' 
#' ## SQL("SELECT * FROM mytable ") + "WHERE id ='"  + 1:10 + "'"
#' ## <SQL> SELECT * FROM mytable WHERE id ='1'
#' ## <SQL> SELECT * FROM mytable WHERE id ='2'
#' ## <SQL> SELECT * FROM mytable WHERE id ='3'
#' ## <SQL> SELECT * FROM mytable WHERE id ='4'
#' ## <SQL> SELECT * FROM mytable WHERE id ='5'
#' ## <SQL> SELECT * FROM mytable WHERE id ='6'
#' ## <SQL> SELECT * FROM mytable WHERE id ='7'
#' ## <SQL> SELECT * FROM mytable WHERE id ='8'
#' ## <SQL> SELECT * FROM mytable WHERE id ='9'
#' ## <SQL> SELECT * FROM mytable WHERE id ='10'
#' 
"+.SQL" <- function(a,b) {SQL(paste0(a,b))}
```

**Comment by krlmlr** [comment]
Thanks. If _dbx_ adopts `dbxSQL()`, the `+` operator (perhaps implemented as S4 method?) could also live there. I'd rather not expand _DBI_ in this direction at this time.
