### ISSUE TITLE
Consider standard timezone and timezone_out arguments to dbConnect()

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#269]
https://github.com/r-dbi/RMariaDB/issues/93#issuecomment-405058247

With tests.

**Comment by hannesmuehleisen** [comment]
So the behaviour would be to convert posixct returned by db to this time zone?

**Comment by krlmlr** [comment]
Yes. The other behavior would be to add timezone information to columns that are flagged as "local time", e.g. in MariaDB, so that the time comes out correctly. Also important for datetime -> date coercions.
