### ISSUE TITLE
dbWriteTable function in DBI package is throwing an error

### ISSUE THREAD

**Issue by shreyas2290** [r-dbi/DBI#270]
I am trying to upload a dataframe to presto server. It is showing the following error:
"Error in .verify.JDBC.result(r, "Unable to retrieve JDBC tables list") : Unable to retrieve JDBC tables list ()"

Code Used:
dbWriteTable(conn,DBI::SQL("test.demo"),value =  df)

I have also tried using insert into, create, drop commands in dbSendQuery with the same connection and it is working perfectly. I am facing issue when I use dbWriteTable function. 

**I have tried other functions of the DBI package like dbReadTable, dbCreateTable too which is working perfectly for me.** 

Please help!

**Comment by krlmlr** [comment]
Thanks. Can you please take this to the [_RJDBC_ issue tracker](https://github.com/s-u/RJDBC/issues)? If you do, please also mention the StackOverflow question https://stackoverflow.com/q/54070867/946850, which does look very similar.
