### ISSUE TITLE
dbVersion(con) generic?

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBI#271]
Should we have a standard way of getting the server database version?

**Comment by krlmlr** [comment]
We had this in `dbGetInfo()`, this is somewhat in a limbo state. For what other parts of that information should we provide generics? Perhaps we can also standardize what `dbGetInfo()` returns?

**Comment by krlmlr** [comment]
Please use `dbGetInfo()` to retrieve the relevant information.
