### ISSUE TITLE
Feature Request: sending multiple "blocks" of SQL code to DB.

### ISSUE THREAD

**Issue by dje7** [r-dbi/DBI#273]
I am transitioning over to R from Toad Data Point so that my data gathering/cleaning/analysis can all be in R. I have multiple instances where in order to get to the dataset I will use for the analysis I have had to create a large number of intermediary tables under my schema. 
Each "block" normally starts:
DROP TABLE A;
CREATE TABLE A as
SELECT ......
FROM ....
; COMMIT;

DROP TABLE B;
CREATE TABLE B as
SELECT ......
FROM ....
; COMMIT;

I want to be able  execute all of the queries that I need (DROP Table, CREATE Table, UPDATE Table, etc.) and then only bring over to TOAD the final table(s)  I need from my schema.

My apologies if this function already exists. I've not been able to find it.

**Comment by krlmlr** [comment]
Or [_dbr_](https://github.com/daroczig/dbr)?
