### ISSUE TITLE
Add ability to limit the number of records returned by dbReadTable

### ISSUE THREAD

**Issue by ronblum** [r-dbi/DBI#275]
It would be useful to specify the number of rows returned by `dbReadTable`. Something like
```
dbReadTable(con, "myTable", n = 10)
```

This would be the equivalent of 
```
SELECT * from myTable LIMIT 10
SELECT TOP 10 * from myTable
```
etc., depending on the database's syntax.

**Comment by krlmlr** [comment]
Duplicate of #240.
