### ISSUE TITLE
Driver object should optionally contain connection information

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#280]
Hannes suggests to store the information how to connect, i.e. the arguments to `dbConnect()`, in the driver object.

Solves a bunch of problems:

- reconnecting
- context for DBItest
- configuration of test databases

CC @hannesmuehleisen.

**Comment by jimhester** [comment]
Is there any concern this would increase the chances of exposing db passwords inadvertently? Obviously this is not really a concern in the testing cases.

**Comment by krlmlr** [comment]
We could do something like

```r
drv <- RPostgres(..., password = function() get_password_from_keychain(...))
```

and have `dbConnect()` call the password getter upon connecting. Or partial specification:

```r
drv <- RPostgres(...)
dbConnect(drv, password = ...)
```

**Comment by krlmlr** [comment]
- [ ] private `.conn_args` slot
- [ ] getter
- [ ] setter
- [ ] ensure arguments are picked up by `dbConnect()`

Maybe a new `"DBIConnector"` class, inheriting from `"DBIDriver"`, could take care of forwarding to bare `dbConnect()`, to minimize downstream implementation effort?

**Comment by krlmlr** [comment]
Prefer aggregation over inheritance, they say.

**Comment by krlmlr** [comment]
Restrictions for arguments:

- must be named
- must not contain `drv`

**Comment by krlmlr** [comment]
Pros of a new connector class:

- works immediately across all backends

Cons:

- it's possible to create a connector object with invalid argument names -- checking arguments still is the responsibility of `dbConnect()`
- if we want to support `RSQLite::SQLite()` returning a connector object instead of a driver, we need to tweak DBItest and perhaps implement `dbDriver("DBIConnector")`

**Comment by krlmlr** [comment]
Needs documentation tweaks.

**Comment by hannesmuehleisen** [comment]
Would be nice to have a `close()` method or something of the like

**Comment by krlmlr** [comment]
I forgot -- what do we need a `close()` method for?
