### ISSUE TITLE
Add links to DBI documentation

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#287]
Backends should link prominently to DBI documentation from their README article and from the methods.

Users start with the question: "Can I connect from R to my favorite database?" They may be unaware of the methods in DBI and where to look for documentation.

**Comment by mbannert** [comment]
Let me weigh in our discussion here and show an example of what could be documented better: 

Even if I figure `Postgres` handles `dbBind` differently than let's say MySQL and therefore go to 

https://rpostgres.r-dbi.org/

the very first bullet and link to `dbSendQuery` leads here: https://rdrr.io/cran/DBI/man/dbSendQuery.html

and the example of a parameterized query does not work:

```
rs <- dbSendQuery(con, "SELECT * FROM mtcars WHERE cyl = ?")
```

At least preparing the above query did not work for me on PostgreSQL 9.6 for me. 
I got 

```
 Error in result_create(conn@ptr, statement) : 
  Failed to prepare query: ERROR:  syntax error at end of input
LINE 1: SELECT * FROM xxx WHERE yyy = ?
```
for my table. Using `$1` worked for me which is in line with the [PostgreSQL documentation](https://www.postgresql.org/docs/9.2/sql-prepare.html). I also looked it up in more recent [versions of PostgreSQL](https://www.postgresql.org/docs/11/sql-prepare.html) and the syntax does not change. 

Let me know if I can help here maybe with a PR for the DBI or the Postgres specific pkg down documentation.

**Comment by krlmlr** [comment]
Thanks. This example clearly shows that we need to do better.

So far the specs only mention that the placeholder syntax is database dependent (#52). I think that a paragraph or two in `?dbSendQuery` and friends is warranted, or perhaps a dedicated help page or article.

We have https://rpostgres.r-dbi.org/reference/postgres-query.html but the documentation there is lacking too.

Maybe, as first steps:

- [ ] add a help page in DBI explaining the situation with the placeholders, with examples for different backends
- [ ] clearly link to this help page from the documentation of parameters in `?dbSendQuery` and friends
- [ ] add more detail to `?RPostgres::dbSendQuery` and related functions and related packages
- [ ] make sure that `?dbSendQuery` links to all other known implementations of `dbSendQuery` on the pkgdown site, using a static list of packages derived using code in #274 (currently we have dynamic linking in R when the backend is loaded)

Which of these items do you think have the most impact? Do you have other ideas?

**Comment by mbannert** [comment]
I will revisit this in greater detail next week. In the very short run, I guess a simple **bold** note in here: https://rpostgres.r-dbi.org/ right were `dbSendQuery` and `dbBind` would have the most impact. 

Something like: **PostgreSQL has its own specific bind parameter Syntax for prepared queries** We also might want to link to the documentation of *prepare* in Postgres. Besides, your ideas are good, I'll try to come up with some structural suggestions next week.

**Comment by krlmlr** [comment]
DBI now links to all known backends from all methods, in particular `?dbConnect` will be most helpful. Closing for now.
