### ISSUE TITLE
Is it intended that DBI::Id() does not have a `as.character()` method?

### ISSUE THREAD

**Issue by jimhester** [r-dbi/DBI#298]
Using `DBI::Id()` objects in places that convert objects to characters results in an error.

``` r
as.character(DBI::Id(blah = "foo"))
#> Error in as.character.default(DBI::Id(blah = "foo")): no method for coercing this S4 class to a vector
paste(DBI::Id(blah = "foo"))
#> Error in as.character.default(new("Id", name = c(blah = "foo"))): no method for coercing this S4 class to a vector
```

<sup>Created on 2020-01-10 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I see there is a `toString()` method defined for these objects, is the intention that all coercion to strings must be explicit and use `toString()`?

Ref: https://github.com/r-dbi/odbc/issues/339

**Comment by krlmlr** [comment]
I guess so. I'd expect users to call `dbQuoteIdentifier(con, id)` to retrieve a printable representation. I was not aware of `toString()`.

**Comment by krlmlr** [comment]
`toString.Id()` was effectively introduced in 18c8e85501d3bf4b853d91f3bedb6eb737a4c46f and last touched in 31bd35f0e37b84a8a79a088957ac0334ad6b9325. I now consider breaking `paste()` a feature.
