### ISSUE TITLE
partitioned tables in bigquery

### ISSUE THREAD

**Issue by MaximumV** [r-dbi/DBI#303]
Hi! Pls kindly advice on how to create partitioned tables in bigquery
I know that this is a little bit aside from your great package, but if you could advice it would be much appreciated!

**Comment by krlmlr** [comment]
This sort of question is a better fit for https://community.rstudio.com. Do you mind asking it over there? (You might want to read https://www.tidyverse.org/help/ first to maximize your chances of getting a good answer.)
