### ISSUE TITLE
unable to find an inherited method for function ‘dbQuoteLiteral’ for signature ‘"Pool"

### ISSUE THREAD

**Issue by Chrisjb** [r-dbi/DBI#308]
No reprex because this is running on a server but my same code runs in development environment locally with no issue. Hoping someone will be able to look at the error and make sense of what's going wrong. Long shot I know.

> <simpleError in (function (classes, fdef, mtable) {    methods <- .findInheritedMethods(classes, fdef, mtable)    if (length(methods) == 1L)         return(methods[[1L]])    else if (length(methods) == 0L) {        cnames <- paste0("\"", vapply(classes, as.character,             ""), "\"", collapse = ", ")        stop(gettextf("unable to find an inherited method for function %s for signature %s",             sQuote(fdef@generic), sQuote(cnames)), domain = NA)    }    else stop("Internal error in finding inherited methods; didn't return a unique method",         domain = NA)})(list("Pool"), new("standardGeneric", .Data = function (conn,     x, ...) standardGeneric("dbQuoteLiteral"), generic = structure("dbQuoteLiteral", package = "DBI"),     package = "DBI", group = list(), valueClass = character(0),     signature = c("conn", "x"), default = NULL, skeleton = (function (conn,         x, ...)     stop("invalid call in method dispatch to 'dbQuoteLiteral' (no default method)",         domain = NA))(conn, x, ...)), <environment>): unable to find an inherited method for function ‘dbQuoteLiteral’ for signature ‘"Pool"’>

**Comment by krlmlr** [comment]
Thanks.

> unable to find an inherited method for function ‘dbQuoteLiteral’ for signature ‘"Pool"’>

Looks like the {pool} package needs a `dbQuoteLiteral()` method, CC @jcheng5.

**Comment by krlmlr** [comment]
Can you please file at https://github.com/rstudio/pool, with a reprex?

**Comment by Chrisjb** [comment]
As I say, I can't reproduce this as it doesn't happen in my development environment for some reason. I'm running a simple query with `sf` and `read_sf` on a postgis database. I fixed it by using `poolCheckout` and `poolReturn` but I can't see why I needed to do that. Anyway it seems not an issue for DBI you're right.
