### ISSUE TITLE
Package for defining and documenting database schemas and structures

### ISSUE THREAD

**Issue by georgevbsantiago** [r-dbi/DBI#312]
Hello,
Is there any intention to develop a package that to define and document database schemas and structures?

I saw this project and found it very interesting. They developed a language for this called DBML (Database Markup Language).

https://dbdiagram.io/home

https://www.dbml.org/home/#intro

Would it be too complex to develop a wrapper package in R language?

**Comment by krlmlr** [comment]
Thanks for raising this. This looks like a good fit for the [dm package](https://krlmlr.github.io/dm/). Would you like to contribute there?

The `dm_paste()` method with its most recent extension (https://github.com/krlmlr/dm/pull/314) seems to do what DBML does, minus the SQL-specific type extensions. Looking for a way to incorporate these too.
