### ISSUE TITLE
Append table to an existing one while removing all duplicated rows

### ISSUE THREAD

**Issue by GitHunter0** [r-dbi/DBI#319]
Is it possible to append a table to an existing one while removing all duplicated rows? 

If not, what do you think about an extra option like this `dbWriteTable(append=TRUE, remove_duplicates=TRUE)` ?

Using queries via dplyr for example would require to rewrite the entire table, which can take a long time if it is big.

It would be great to have methods to easily update and modify existing tables without the need to rewriting them completely.

Thank you very much, DBI is a fantastic package.

**Comment by krlmlr** [comment]
This is out of scope for DBI, eventually `dplyr::rows_upsert()` and friends will work for databases. Some methods are currently provided in the dm package.
