### ISSUE TITLE
Oracle Idle timeout override

### ISSUE THREAD

**Issue by andybeet** [r-dbi/DBI#323]
On our servers Oracle has a 15 minute idle timeout. For applications like SQLDeveloper there is a "keep alive" feature which overrides this. When i connect to Oracle using R: 

```r
con <- DBI::dbConnect(odbc::odbc(),dsn,uid,pwd)
```

the connection is dropped after a period of time. This becomes problematic for db connections in shiny apps

Can a similar override be implemented in DBI?

**Comment by krlmlr** [comment]
Thaks. What does `dbValid(con)` return after timeout?

**Comment by andybeet** [comment]
Thanks for your quick response.

Where is the function `dbValid `? I don't see is as part of the DBI package.
Are you referring to `dbIsValid`?

**Comment by krlmlr** [comment]
Could the pool package help here?

**Comment by krlmlr** [comment]
Not sure, if `dbIsValid()` doesn't detect the condition, and pool doesn't even call `dbIsValid()` .

**Comment by krlmlr** [comment]
If "keep alive" means that you need to send a query every x minutes to keep the connection alive, I think this could be achieved with the later package.

**Comment by andybeet** [comment]
> If "keep alive" means that you need to send a query every x minutes to keep the connection alive, I think this could be achieved with the later package.

Yes, this is what i mean. A lack of activity (> 15 min without a query) then the connection object isn't recognized as valid by the db. I looked over the `pool` package and it does seem to address this. I will implement it and test.
Thanks for you help/advice
