### ISSUE TITLE
SQL statements must be issued with dbExecute() or dbSendStatement() instead of dbGetQuery() or dbSendQuery().

### ISSUE THREAD

**Issue by dcassol** [r-dbi/DBI#347]
I would like to create a new database, which returns the results of a query as a dataframe. If I use dbExecute() or dbSendStatement(), as indicated in the warning message, it won't return the required dataframe. What can I do to remove this warning?

```r
drv <- RSQLite::dbDriver("SQLite")
con <- DBI::dbConnect(drv, dbname= tempfile())
DBI::dbGetQuery(con, paste("CREATE TABLE activity",
        "(aid INTEGER, cid INTEGER,",
        "activity INTEGER, score REAL)"))
# data frame with 0 columns and 0 rows
# Warning message:
# In result_fetch(res@ptr, n = n) :
#  SQL statements must be issued with dbExecute() or dbSendStatement() instead of dbGetQuery() or dbSendQuery().
```

Thank you very much! :)

**Comment by krlmlr** [comment]
Thanks. What response do you expect from this query? The table is empty initially, the query usually doesn't return anything even on the sqlite shell.
