### ISSUE TITLE
Allow creation of tables with primary key and/or index

### ISSUE THREAD

**Issue by pnacht** [r-dbi/DBI#353]
The title is pretty self-explanatory.

Primary keys and indices are essential tools for performant SQL queries, but must currently be performed manually by the user after table creation with an `ALTER TABLE` call (made more complex for PK's by the fact that the respective columns must be NOT NULL, which must also be defined post-facto).

At a glance, at least PK's could be relatively simply implemented by adding an argument to `dbCreateTable` and modifying `sqlCreateTable`. Indices are made more complicated by the need to define them as clustered or non-clustered, but PK's seem quite simple (says the guy who hasn't actually tried doing it).

**Comment by krlmlr** [comment]
Thanks. Would you like to test-drive #351?

**Comment by krlmlr** [comment]
Might be easier with a rewrite. Closing for now.
