### ISSUE TITLE
dbAppendTable does not work with temporary tables

### ISSUE THREAD

**Issue by bwohl** [r-dbi/DBI#354]
As of version 1.1.1 it doesn't seem to be possible to use dbAppendTable with temporary tables. 
This seems to be due to a check of dbExistsTable which returns FALSE for temporary tables. 
I tested this with R 4.1.0, DBI 1.1.1 (vs. 1.1.0), SQL Server 13.0.5888.11

``` r

df <- data.frame(col1 <- c("test"))

sourceTable = paste0("##", do.call(paste0, replicate(7, sample(LETTERS, 1, TRUE), FALSE)))
DBI::dbCreateTable(con, sourceTable, df, temporary = TRUE)
DBI::dbExistsTable(con, sourceTable)
#> [1] FALSE
DBI::dbAppendTable(con, sourceTable, df)
#> Error in DBI::dbAppendTable(con, sourceTable, df): dbExistsTable(conn, name) is not TRUE


```

**Comment by krlmlr** [comment]
Thanks. This is likely due to a change in odbc, not DBI. Can you please double-check?

**Comment by bwohl** [comment]
Sorry, I thought before I could get it to work by downgrading DBI, but you are right the issues is in odbc.
