### ISSUE TITLE
DBI::dbWithTransaction fails when working with ROracle drivers due to DBI::dbBegin dependency

### ISSUE THREAD

**Issue by mmccarthy404** [r-dbi/DBI#355]
dbWithTransaction makes use of dbBegin in it's source code, however, ROracle doesn't handle the dbBegin method, which makes it impossible to run DBI::dbWithTransaction on Oracle databases.

**Comment by krlmlr** [comment]
Thanks. I think we need to implement either `dbBegin()` or `dbWithTransaction()` for the corresponding class. Ideally this is done in the ROracle package, you can also work around in user code:

```r
setMethod("dbWithTransaction", signature("OracleConnection"), function(conn, code) {
  message("dbWithTransaction() not implemented for Oracle connections.")
  code
})
```
