### ISSUE TITLE
How to prevent / change quoting of `name` argument in `db*()` functions?

### ISSUE THREAD

**Issue by matthiasgomolka** [r-dbi/DBI#374]
I connect to a Hive Database using an ODBC connection. Executing queries works fine, as long as I write the SQL code myself.

For example, this works:

```r
dbExecute(
  conn,
  "CREATE TABLE db_name.iris (
    sepal_length DOUBLE, 
    sepal_width DOUBLE, 
    petal_length DOUBLE, 
    petal_width DOUBLE, 
    species STRING
  )"
)
```

But when I want to create the same table using `DBI::dbCreateTable()` I get an error:

```r
> dbCreateTable(conn, "db_name.iris", fields = iris)
Error: nanodbc/nanodbc.cpp:1617: 42000: [Cloudera][Hardy] (80) Syntax or semantic analysis error thrown in server while executing query. Error message from server: Error while compiling statement: FAILED: SemanticException Line 1:13 Table or database name may not contain dot(.) character 'datalab_aidatest.iris_managed2' 
<SQL> 'CREATE TABLE `db_name.iris` (
  `sepal_length` DOUBLE,
  `sepal_width` DOUBLE,
  `petal_length` DOUBLE,
  `petal_width` DOUBLE,
  `species` STRING
)
'
```

From what I understood from googling, this is related to the type of quoting of the table name. For example, if I send the SQL code directly, it works if the table is quoted like this: 

```r
`db_name`.`iris`
``` 

The `DBI::dbCreateTable()` documentation says about the `name` argument:

> Name of the table, escaped with dbQuoteIdentifier().

So I verified that `DBI::dbQuoteIdentifier(conn, "db_name.iris")` returns 

```r
<SQL> `db_name.iris`
```

As far as I understand, if it would be possible to change or prevent this type of default quoting, I would be able to use `DBI::dbCreateTable()` for my HIVE Database.

Is there a possibility to prevent the quoting or to change it's behavior?

Please be patient if I'm overlooking something obvious. I'm rather new to working with databases.

**Comment by krlmlr** [comment]
Thanks, it's a bit convoluted. You should be able to use either of:

```r
DBI::dbQuoteIdentifier(conn, DBI::Id(schema = "db_name", table = "iris"))
DBI::SQL("db_name.iris")
```

How should we improve the documentation to make this more accessible?

**Comment by matthiasgomolka** [comment]
Thanks for the very quick response! Now it works!

Actually, I think the documentation is pretty good. My mistake was that I was using version 1.1.1 when I read the documentation yesterday. When I checked again today (after having updated `DBI` yesterday after having issues), I saw the new version which makes this issue obsolete.

Sorry for bothering you!
