### ISSUE TITLE
`dbAppendTable()` no longer works with `Id`

### ISSUE THREAD

**Issue by renkun-ken** [r-dbi/DBI#380]
See [#253 ](https://github.com/r-dbi/RMariaDB/issues/253)

In previous releases, `dbAppendTable(con, Id(schema = "foo", table = "bar"), data)` works as documented at <https://github.com/r-dbi/DBI/blob/main/R/Id.R#L16> but has stopped working since v1.1.2.

The check at 

https://github.com/r-dbi/DBI/blob/273d195ba9d9c9a5a7bb2ffbc13120a32edb5dd5/R/dbAppendTable_DBIConnection.R#L7

ignores that `name` might be `Id` and `sqlAppendTableTemplate` would call `dbQuoteIdentifier` with the `name` anyway.

https://github.com/r-dbi/DBI/blob/273d195ba9d9c9a5a7bb2ffbc13120a32edb5dd5/R/sqlAppendTableTemplate.R#L26

Does it make sense if we remove the check of `name` in `sqlAppendTableTemplate` or allow it to be `Id`?

**Comment by krlmlr** [comment]
Thanks, makes sense. We also need a test in DBItest.

**Comment by renkun-ken** [comment]
Do you prefer simply removing the check or allowing it to be `Id` in the check?

**Comment by krlmlr** [comment]
Should we check after calling `dbQuoteIdentifier()` ?

**Comment by renkun-ken** [comment]
Looks like `dbQuoteIdentifier` already does all necessary checks.
