### ISSUE TITLE
dbConnect fails with no error message

### ISSUE THREAD

**Issue by fnavarro94** [r-dbi/DBI#384]
I am trying to use DBI to connect to a postgres database.  When I use dbConnect() it fails with no error message and outputs some symbols. Not sure what is causing this. Any help will be much appreciated

```r
drv <- dbDriver("PostgreSQL")


dbConnect(drv, host=Sys.getenv('DB_HOST'),
                      port=Sys.getenv('DB_PORT'),
                      dbname=Sys.getenv('DB_NAME'), 
                      user=Sys.getenv('DB_USER'), 
                      password=Sys.getenv('DB_PASSWORD'))

```

I get that output regardless of the values of  host,  port, dbname, user and   password I use. In fact If I run only this

```r
drv <- dbDriver("PostgreSQL")
dbConnect(drv)
```
I get the same output.

![image](https://user-images.githubusercontent.com/25945561/161155445-6925d5ae-66c3-41a6-9db7-ae81119f94c0.png)

![image](https://user-images.githubusercontent.com/25945561/161156250-ff87d488-468f-4e62-b7cf-5c178e5240ec.png)

**Comment by krlmlr** [comment]
Thanks. Can you try reinstalling the RPostgreSQL package, or try with the RPostgres package?

**Comment by fnavarro94** [comment]
Thanks for the quick responce. I just tried that. I get the same output for both RPostgreSQL and RPostgres

**Comment by krlmlr** [comment]
What does the `dbConnect()` call look like that you use to connect via RPostgres?
