### ISSUE TITLE
dbFetch() documentation needs more documentation about overall flow

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBI#386]
i.e.:

* Use `dbSendQuery()` to get a result set
* Optionally bind paremeters with `dbBind()`.
* Use `dbFetch()` to get a page of results
* Use `dbHasCompleted()` to tell when you're done
* Use `dbClearResult()` to clean up 

And it might be worth linking all these functions together with a common family.

**Comment by krlmlr** [comment]
Almost forgot, see d2bf235 for a proposal. Releasing today, we can tweak later.

**Comment by krlmlr** [comment]
Next try: 7abf906cf21f150caef996aca2573ef7c0dafc6a.

**Comment by krlmlr** [comment]
Done and on its way to CRAN, see https://dbi.r-dbi.org/reference/dbsendquery for the rendered version.

Still happy to take feedback.

CC @hannes.

**Comment by hadley** [comment]
LGTM.
