### ISSUE TITLE
Error: Supplied values don’t match named vars to interpolate

### ISSUE THREAD

**Issue by scottfrechette** [r-dbi/DBI#394]
I’m getting an error that says “Supplied values don’t match named vars to interpolate” when using pivot_longer() in sparklyr but have no issues  when using dplyr locally on same data. 

I looked in documentation and wonder if the `d = 2` should be `b = 2` here:

```
test_that("named parameters check matches", {
  expect_error(
    [sqlInterpolate](https://rdrr.io/github/r-dbi/DBI/man/sqlInterpolate.html)([ANSI](https://rdrr.io/github/r-dbi/DBI/man/ANSI.html)(), "?a ?b", a = 1, d = 2),
    "Supplied values don't match named vars to interpolate"
  )
})
```

**Comment by krlmlr** [comment]
Thanks. Are you referring to this test?

https://github.com/r-dbi/DBI/blob/ef890bceb4bc9a262a3f3410b72e0d060f8968e2/tests/testthat/test-interpolate.R#L32-L37

The test here checks that an error is thrown if names are mismatched, should be good.

Other than that, can you please raise this at https://community.rstudio.com/ ?
