### ISSUE TITLE
dbplyr 2.4.0- breaking changes

### ISSUE THREAD

**Issue by kelseyroberts** [r-dbi/DBI#426]
With the updates to dbplyr version 2.4.0 it seems like some of the arguments that worked in the previous version, I was using version 2.3.2,  no longer work. 

The 3 main differences we are seeing is 
1. The "database" argument needs to be called “catalog” now
2. "schemaname" needs to be called “schema” 
3. "tablename" needs to be called “table”

---

Database to catalog 
For example this call used to work with the argument “database”:

```r
database_connection_object%>%
  tbl(DBI::Id(
    database = "db1",
    schema = "schema1",
    table = "table1"
  )) %>%
  collect()
```
This now requires “database” to be named “catalog” as seen below:
```r
database_connection_object%>%
  tbl(DBI::Id(
    catalog = "db1",
    schema = "schema1",
    table = "table1"
  )) %>%
  collect()
```

Schemaname and Tablename
“schemaname” and “tablename” were arguments that worked before and are now also giving errors: 
```r
database_connection_object%>%
  tbl(DBI::Id(
    database = "db1",
    schemaname = "schema1",
    tablename = "table1"
  )) %>%
  collect()
```

schemaname and tablename now are required to be “schema” and “table”:
```r
database_connection_object%>%
  tbl(DBI::Id(
    database = "db1",
    schema= "schema1",
    table= "table1"
  )) %>%
  collect()
```

**Comment by krlmlr** [comment]
Thanks. What DBI backend are you using? Can you please share the code that establishes the database connection?

**Comment by kelseyroberts** [comment]
I moved this issue to the dbplyr! I will close this one!

**Comment by kelseyroberts** [comment]
Moved issue to dbplyr
