### ISSUE TITLE
website cert problem

### ISSUE THREAD

**Issue by r2evans** [r-dbi/DBI#468]
I don't know who maintains the `r-dbi.org` domain, but its certificate is currently wrong.

![image](https://github.com/r-dbi/DBI/assets/5815808/b522f91f-19b1-410c-be5d-6882b250738b)

![image](https://github.com/r-dbi/DBI/assets/5815808/90b262c1-9c38-46a5-a029-921fca174117)

**Comment by krlmlr** [comment]
Works for me. Does the issue persist?

**Comment by r2evans** [comment]
Yes, on FF and Chrome, same results as above.

The output from `echo '' | openssl s_client -connect r-dbi.org:443` (below) lists the CN as "Netlify, Inc". If I do the same comment but for `dbi.r-dbi.org` instead (also included below), it lists the CN as `dbi.r-dbi.org`.

Bottom line, it looks like the cert covers `*.r-dbi.org` but not `r-dbi.org`.

<details><summary><code>openssl s_client -connect r-dbi.org:443</code></summary>

<pre>
CONNECTED(00000003)
depth=2 C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
verify return:1
depth=1 C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1
verify return:1
depth=0 C = US, ST = California, L = San Francisco, O = "Netlify, Inc", CN = *.netlify.app
verify return:1
---
Certificate chain
 0 s:C = US, ST = California, L = San Francisco, O = "Netlify, Inc", CN = *.netlify.app
   i:C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1
   a:PKEY: id-ecPublicKey, 256 (bit); sigalg: RSA-SHA256
   v:NotBefore: Jan 15 00:00:00 2024 GMT; NotAfter: Feb 14 23:59:59 2025 GMT
 1 s:C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1
   i:C = US, O = DigiCert Inc, OU = www.digicert.com, CN = DigiCert Global Root G2
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar 30 00:00:00 2021 GMT; NotAfter: Mar 29 23:59:59 2031 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIGGDCCBQCgAwIBAgIQA+0WeiZZ2ieOeyHNvrM+MjANBgkqhkiG9w0BAQsFADBZ
MQswCQYDVQQGEwJVUzEVMBMGA1UEChMMRGlnaUNlcnQgSW5jMTMwMQYDVQQDEypE
aWdpQ2VydCBHbG9iYWwgRzIgVExTIFJTQSBTSEEyNTYgMjAyMCBDQTEwHhcNMjQw
MTE1MDAwMDAwWhcNMjUwMjE0MjM1OTU5WjBpMQswCQYDVQQGEwJVUzETMBEGA1UE
CBMKQ2FsaWZvcm5pYTEWMBQGA1UEBxMNU2FuIEZyYW5jaXNjbzEVMBMGA1UEChMM
TmV0bGlmeSwgSW5jMRYwFAYDVQQDDA0qLm5ldGxpZnkuYXBwMFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEZMOrg6Gfm/f/5QC/Qa7N0c0cXY1NYvsO5JAzEy21RZHm
eiagXgGuJYT71YgjfhN+qdOl3mktkWnDEoZalAJCKKOCA5UwggORMB8GA1UdIwQY
MBaAFHSFgMBmx9833s+9KTeqAx2+7c0XMB0GA1UdDgQWBBQ+ar5uJawSEKu+8eun
qbxtiH1UjzAlBgNVHREEHjAcgg0qLm5ldGxpZnkuYXBwggtuZXRsaWZ5LmFwcDA+
BgNVHSAENzA1MDMGBmeBDAECAjApMCcGCCsGAQUFBwIBFhtodHRwOi8vd3d3LmRp
Z2ljZXJ0LmNvbS9DUFMwDgYDVR0PAQH/BAQDAgOIMB0GA1UdJQQWMBQGCCsGAQUF
BwMBBggrBgEFBQcDAjCBnwYDVR0fBIGXMIGUMEigRqBEhkJodHRwOi8vY3JsMy5k
aWdpY2VydC5jb20vRGlnaUNlcnRHbG9iYWxHMlRMU1JTQVNIQTI1NjIwMjBDQTEt
MS5jcmwwSKBGoESGQmh0dHA6Ly9jcmw0LmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEds
b2JhbEcyVExTUlNBU0hBMjU2MjAyMENBMS0xLmNybDCBhwYIKwYBBQUHAQEEezB5
MCQGCCsGAQUFBzABhhhodHRwOi8vb2NzcC5kaWdpY2VydC5jb20wUQYIKwYBBQUH
MAKGRWh0dHA6Ly9jYWNlcnRzLmRpZ2ljZXJ0LmNvbS9EaWdpQ2VydEdsb2JhbEcy
VExTUlNBU0hBMjU2MjAyMENBMS0xLmNydDAMBgNVHRMBAf8EAjAAMIIBfQYKKwYB
BAHWeQIEAgSCAW0EggFpAWcAdQBOdaMnXJoQwzhbbNTfP1LrHfDgjhuNacCx+mSx
Ypo53wAAAY0Mu8dlAAAEAwBGMEQCIB7FL3xLGY4wUvKb3l9Q+ZjOP1pLEC2L4XpJ
+nwXC+fHAiBp1IcuRkk+Ig6W5pq8iyJoPWJ4ejltwvH/crTsyrtz0AB1AH1ZHhLh
eCp7HGFnfF79+NCHXBSgTpWeuQMv2Q6MLnm4AAABjQy7x2cAAAQDAEYwRAIgFGLu
WY42+ip1EhACdAOTmmfTgJVNdcwuPv0k4xhDo88CICAKpid4QSG5gPsgYz5Lb6R1
FQKlXNK0OGQzINQ81UY3AHcA5tIxY0B3jMEQQQbXcbnOwdJA9paEhvu6hzId/R43
jlAAAAGNDLvHkQAABAMASDBGAiEAhp9eEk3bj4ys1YyA+OKF9jssIbHun/xp9yox
NyNc7dICIQCzCxOD1tV6vnMuxnupZwo6D84IVaDd5gxQGugX6w1ODDANBgkqhkiG
9w0BAQsFAAOCAQEAhRBlqiMZRKCFcOwLCf/HyQY+2Bn2FKrzxbuh4e4c51FpoMYW
w7/o5XWN9dicwSmmlCZq5iatn7OGTqiKkzwKaqfZtZJWUEOPfjDE3NJgJvX6hEom
G2faOMSqORXmRcIFtCzN7WyW/l6Sy/XBitXCxXVZIID1y3WgIeVAKSPjgM0Jiaj2
YLD2dY61byzwQapiWQSDnEfJmwQQsJJDBMGVZ0DOyunP9h7YU9RqysH2Hd94DiBG
vI46/vFaqT5oZgrWDbKwM0/U5c0SsOCj1StQOImrMpcPpoJK2KH3eASXFUQFgIQv
6+eBnQAu+jq7o+c7Iqtszs5lrZqkDGOzItaqhw==
-----END CERTIFICATE-----
subject=C = US, ST = California, L = San Francisco, O = "Netlify, Inc", CN = *.netlify.app
issuer=C = US, O = DigiCert Inc, CN = DigiCert Global G2 TLS RSA SHA256 2020 CA1
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: ECDSA
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3152 bytes and written 375 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_128_GCM_SHA256
Server public key is 256 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
---
Post-Handshake New Session Ticket arrived:
SSL-Session:
    Protocol  : TLSv1.3
    Cipher    : TLS_AES_128_GCM_SHA256
    Session-ID: C3194E40D261E0890E69E7900B15EBFC9AF4D9ED52220297F203F275E482FAEB
    Session-ID-ctx: 
    Resumption PSK: E0EF10CF69FD53FBB1A55435E57E2E7CB5C33BD6C365DADF6308DA8FAEE47073
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 604800 (seconds)
    TLS session ticket:
    0000 - 07 55 b8 46 e2 3b 9b c2-76 8e c5 cd 30 d4 c6 e8   .U.F.;..v...0...
    0010 - 30 12 25 ab 98 84 5a 1f-40 6b 67 44 4e c3 b1 fd   0.%...Z.@kgDN...
    0020 - e7 dd fd 9c 33 5d a7 1a-fe 61 47 6a 15 cf c7 d7   ....3]...aGj....
    0030 - a1 a5 6e 30 2c 39 66 d3-74 6d 3c 41 9b 0b f2 c1   ..n0,9f.tm<A....
    0040 - ba 5e 9d 3f 17 43 6f 26-39 5d be dd 1f 47 ac bf   .^.?.Co&9]...G..
    0050 - f8 ac 68 b8 35 82 3c aa-a0 5a 84 dc ce bd 4f 4d   ..h.5.<..Z....OM
    0060 - 30 24 7d 6f 0e ae c2 ce-3b                        0$}o....;

    Start Time: 1709675561
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: no
    Max Early Data: 0
---
read R BLOCK
DONE
</pre>
</details>

<details><summary><code>openssl s_client -connect dbi.r-dbi.org:443</code></summary>

<pre>
depth=2 C = US, O = Internet Security Research Group, CN = ISRG Root X1
verify return:1
depth=1 C = US, O = Let's Encrypt, CN = R3
verify return:1
depth=0 CN = dbi.r-dbi.org
verify return:1
DONE
CONNECTED(00000003)
---
Certificate chain
 0 s:CN = dbi.r-dbi.org
   i:C = US, O = Let's Encrypt, CN = R3
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Mar  2 05:29:54 2024 GMT; NotAfter: May 31 05:29:53 2024 GMT
 1 s:C = US, O = Let's Encrypt, CN = R3
   i:C = US, O = Internet Security Research Group, CN = ISRG Root X1
   a:PKEY: rsaEncryption, 2048 (bit); sigalg: RSA-SHA256
   v:NotBefore: Sep  4 00:00:00 2020 GMT; NotAfter: Sep 15 16:00:00 2025 GMT
---
Server certificate
-----BEGIN CERTIFICATE-----
MIIE6DCCA9CgAwIBAgISA8PepC4QZ/hnx3TgPhKlVOx/MA0GCSqGSIb3DQEBCwUA
MDIxCzAJBgNVBAYTAlVTMRYwFAYDVQQKEw1MZXQncyBFbmNyeXB0MQswCQYDVQQD
EwJSMzAeFw0yNDAzMDIwNTI5NTRaFw0yNDA1MzEwNTI5NTNaMBgxFjAUBgNVBAMT
DWRiaS5yLWRiaS5vcmcwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCY
mFjr7Mu2d4HocA6HIjHv0mNjZwGckE4QFpSc9Rm2BTBWtoJBYtQxC3nA1OHBNhMf
XHAWIdAcUxOMPAyMXRVH+MeUKUGPwuOyKbYbd42oc+rYY5E30iZQYaEEvfp2Igal
oD3cB0uPtwYktheSLsmu3BYsLMNslCMtn53UQNqYJj1nhze2TKSj7lIx44cs7Tju
cKW1mH3Dh5b7LkVsomwk/2NCtuR81F9rlnMkegyliWiG8XEDeVMOiBxuWqXwgAxm
DaSiILW5CRwANY88iaeKjE5X/R4oGTpj0FYD6fUyDTdAP5qQcTPX17R+QUi0BaqO
92U2h4dmyv9tg0PvSKyNAgMBAAGjggIQMIICDDAOBgNVHQ8BAf8EBAMCBaAwHQYD
VR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUFBwMCMAwGA1UdEwEB/wQCMAAwHQYDVR0O
BBYEFFjJsqpo5qVIzNgr6EKyv3++RWZoMB8GA1UdIwQYMBaAFBQusxe3WFbLrlAJ
QOYfr52LFMLGMFUGCCsGAQUFBwEBBEkwRzAhBggrBgEFBQcwAYYVaHR0cDovL3Iz
Lm8ubGVuY3Iub3JnMCIGCCsGAQUFBzAChhZodHRwOi8vcjMuaS5sZW5jci5vcmcv
MBgGA1UdEQQRMA+CDWRiaS5yLWRiaS5vcmcwEwYDVR0gBAwwCjAIBgZngQwBAgEw
ggEFBgorBgEEAdZ5AgQCBIH2BIHzAPEAdwBIsONr2qZHNA/lagL6nTDrHFIBy1bd
LIHZu7+rOdiEcwAAAY392tiCAAAEAwBIMEYCIQCni/LoVbF0ajYQ3ZdSF0TNn6Lm
dQZTN3qIL8P+CVAf/wIhAIEnAJnzQP/dPEKoIDlst5wJjkKA9TOez+Wb0X9F7yd3
AHYAouK/1h7eLy8HoNZObTen3GVDsMa1LqLat4r4mm31F9gAAAGN/drYlgAABAMA
RzBFAiAEMZN2fISzH86kMZelpmfaY/ktxzNB8IWgEYNuRe7v6gIhAMX3b+e+9PSF
KJrVtjeF0hx0tRNlWv0eH1sM7i9mf8kPMA0GCSqGSIb3DQEBCwUAA4IBAQBPfMOz
1WAge7OSIWl2s0+gSo5BMte2Zs73CHkBW96d9TBC0rOF6pYTT1an13dJYo4RIqMH
fv/Cnf9Wx6G8PzEvMf3Dhx5BD4gNPP4a156haQLu1GLi0AUN3S90gRgY1BaME6Eg
KZzRvjk69zbVX5rC6Wyyl0zdXSyT0Aa+Q3YhpSNIfw165eD/DpvUXJM6ldwgXUEI
BiFg+BeF8WoqlXO2lTY8kfnNYCenByX1nFlYiam92KLY5nKsfpIYBRohPGiTMlmK
E/1Yd40/xkXZpjhJLWtlXo7AxXs42OgLalwaiMGOCi28hlc1X9F4S0ohTh/FVPGy
IGUmg3Hu0OFmq3zg
-----END CERTIFICATE-----
subject=CN = dbi.r-dbi.org
issuer=C = US, O = Let's Encrypt, CN = R3
---
No client certificate CA names sent
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 3065 bytes and written 395 bytes
Verification: OK
---
New, TLSv1.3, Cipher is TLS_AES_256_GCM_SHA384
Server public key is 2048 bit
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
Early data was not sent
Verify return code: 0 (ok)
---
</pre>

</details>

**Comment by krlmlr** [comment]
Thanks, confirming:

```
➜  ~ curl -I https://r-dbi.org
curl: (60) SSL: no alternative certificate subject name matches target host name 'r-dbi.org'
More details here: https://curl.se/docs/sslcerts.html

curl failed to verify the legitimacy of the server and therefore could not
establish a secure connection to it. To learn more about this situation and
how to fix it, please visit the web page mentioned above.
➜  ~ curl -I https://www.r-dbi.org
HTTP/2 200
server: GitHub.com
content-type: text/html; charset=utf-8
last-modified: Fri, 16 Feb 2024 07:19:53 GMT
access-control-allow-origin: *
etag: "65cf0c99-760d"
expires: Wed, 06 Mar 2024 05:12:13 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: 3D44:301FA4:681701:6A6107:65E7F8D5
accept-ranges: bytes
date: Wed, 06 Mar 2024 05:02:23 GMT
via: 1.1 varnish
age: 9
x-served-by: cache-ams21069-AMS
x-cache: HIT
x-cache-hits: 1
x-timer: S1709701343.033224,VS0,VE1
vary: Accept-Encoding
x-fastly-request-id: 2aa87cb759beea5f7f731bc86bf81822789e408f
content-length: 30221
```

I wonder why my browser (Firefox) jumps to www.r-dbi.org even if I type in the address verbatim. Some form of caching?

Reviewing now.

**Comment by krlmlr** [comment]
Works now:

```
➜  ~ curl -I https://r-dbi.org
HTTP/2 200
server: GitHub.com
content-type: text/html; charset=utf-8
last-modified: Thu, 14 Mar 2024 07:23:14 GMT
access-control-allow-origin: *
etag: "65f2a5e2-7a59"
expires: Thu, 14 Mar 2024 16:52:20 GMT
cache-control: max-age=600
x-proxy-cache: MISS
x-github-request-id: CC8E:2ECA0:3416AA:34C43C:65F328EC
accept-ranges: bytes
date: Thu, 14 Mar 2024 16:42:20 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-mxp6947-MXP
x-cache: MISS
x-cache-hits: 0
x-timer: S1710434541.792889,VS0,VE113
vary: Accept-Encoding
x-fastly-request-id: 8abfc4bf14354789bb56228f9e931d674c334070
content-length: 31321

➜  ~ curl -I https://www.r-dbi.org
HTTP/2 301
server: GitHub.com
content-type: text/html
location: https://r-dbi.org/
x-github-request-id: 222C:3026BD:6CFD68:6E7943:65F328F6
accept-ranges: bytes
date: Thu, 14 Mar 2024 16:42:30 GMT
via: 1.1 varnish
age: 0
x-served-by: cache-mxp6938-MXP
x-cache: MISS
x-cache-hits: 0
x-timer: S1710434551.506050,VS0,VE98
vary: Accept-Encoding
x-fastly-request-id: bc8eba135639556f0a76883d11cd7de41a37c4ce
content-length: 162
```
