### ISSUE TITLE
relational.fit -> relational-data.org and relational.fel.cvut.cz

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#479]
The site is now available under new URLs. Documentations and server addresses in the code need to be updated.

**Comment by maelle** [comment]
which of the two new URLs should be used?

**Comment by krlmlr** [comment]
For code: Both, the first, and if that doesn't work, the second. 

For the docs: The first, mentioning in one place that the second is a fallback.

Thanks, Maëlle!

**Comment by maelle** [comment]
done in https://github.com/r-dbi/DBI/commit/cad238b3ac6db50eef0f2095d031ddf4fa3bba17

sorry for getting back so late to this!

**Comment by krlmlr** [comment]
Thanks, looks much better now!

**Comment by maelle** [comment]
well you did that commit! I only observed :grin:
