### ISSUE TITLE
Think about field.types argument for sqlCreateTable

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#48]
for easier support of field.types argument to dbWriteTable.

**Comment by krlmlr** [comment]
Related: #61.

**Comment by hadley** [comment]
Ok, currently `fields` can either be a data frame or a named vector. It would be better to just use a named vector of field types. Then the `row.names` argument could also be dropped. 

Might be worthwhile to pull this out as a separate function:

```R
      fields <- rownamesToColumn(fields, row.names)
      fields <- vapply(fields, function(x) DBI::dbDataType(con, x), character(1))
```

**Comment by hadley** [comment]
I think `dbWriteTable()` probably needs a `field_types` argument that overrides the types of the individual columns

**Comment by hannesmuehleisen** [comment]
agreed.

**Comment by krlmlr** [comment]
Part of #74.
