### ISSUE TITLE
Think about dbColumnInfo() and dbFetch() output for unnamed columns

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#50]
Should probably have `NA` in the "name" column, currently it's `"NULL"` or `"?column?"`.

DBItest: "column_info".

**Comment by hadley** [comment]
What does an unnamed column mean in SQL?

**Comment by krlmlr** [comment]
The result of `SELECT 1 UNION SELECT 2` is a two-row table with an unnamed column. It's valid SQL and can occur, and we should be able to handle it reasonably, also in `dbReadTable()`.

**Comment by hadley** [comment]
`SELECT 1 + 2` is an even simpler reprex.  Agreed that NA most is reasonable here.

**Comment by krlmlr** [comment]
Not sure anymore: What should `dbFetch()` return for `SELECT 1, 2`? Data frames with two columns named `""` don't seem to work well. Perhaps we should mandate a naming scheme for unnamed columns (e.g., implement a helper in `DBI`), and use this scheme also in `dbColumnInfo()`.

**Comment by hadley** [comment]
Hmmm, maybe `data.frame(X1 = 1, X2 = 2)` ?  So need to fill in missing variable names with auto generated in both places.

**Comment by krlmlr** [comment]
The data frame should have unique names, even for queries like `SELECT 1, 1`. For SQLite, we can determine if it's a computed column with [`column_database_name()`](https://sqlite.org/c3ref/column_database_name.html), but I'm not sure about other backends. I think we're on the safer side if we don't specify that computed columns need to have artificial names.

**Comment by krlmlr** [comment]
Closing in favor of https://github.com/r-dbi/DBItest/issues/137.
