### ISSUE TITLE
Think about ways to specify placeholder in prepared/parametrized query

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#52]
Used in `dbBind()`. Example (MySQL): `SELECT cast(? as character)`

Postgres: positional, `$1`, `$2`, ...
MySQL: positional, `?`
SQLite: named: `$a` or `:a`, _and_ positional: `?`
Monet-DB: positional, `?`

Similar to `dbQuoteIdentifier()` and `dbQuoteString()`:

```
setMethod("dbQuoteParameter", c("MySQLConnection", "integer"),
  function(conn, n, ...) {
    rep("?", n)
  }
)

setMethod("dbQuoteParameter", c("PqConnection", "integer"),
  function(conn, n, ...) {
    paste0("$", seq_len(n))
  }
)

setMethod("dbQuoteNamedParameter", c("SQLiteConnection", "character"),
  function(conn, param_names, ...) {
    paste0(":", param_names)
  }
)
```

**Comment by hannesmuehleisen** [comment]
MonetDB: positional '?'

**Comment by krlmlr** [comment]
No use case in dplyr currently, leave it for later.

**Comment by krlmlr** [comment]
I think we rather should support a consistent syntax (say, positional "?" and named ":"), and rewrite SQL queries for DBMS that don't support that particular syntax.

**Comment by krlmlr** [comment]
The `sqlInterpolate()` helper defines yet another syntax: Named `?`.

**Comment by krlmlr** [comment]
Would be very nice to have, still.

**Comment by krlmlr** [comment]
Will this be easier to reason about if we define a compound data type for the SQL and the associated params?

```r
con <- dbConnect(RPostgres::Postgres())

query <- SQL("SELECT ?value AS value", dbi_params = list(value = 3))
sqlInterpolate(con, query)
#> SELECT 3 AS value
dbInterpolate(con, query)
# same as SQL("SELECT $1 AS value", params = list(3))
dbGetQuery(con, query)
# same as dbGetQuery(con, dbInterpolate(con, query))
```

**Comment by krlmlr** [comment]
It would be nice to have, but any query rewriting can live in a package outside of DBI, perhaps dbx? We should focus on the basics here.

**Comment by daattali** [comment]
I got here from https://github.com/r-dbi/RPostgres/issues/201
Is there any open issue on any repository that is tracking this?

**Comment by krlmlr** [comment]
Thanks for the pointer. I'm not aware of a repo to track this. I'm collecting those issues in an internal document for now.
