### ISSUE TITLE
Think about fast importing

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#62]
Can it be possibly made portable between DB engines?

**Comment by krlmlr** [comment]
DBMS tend to offer fast-import facilities that are up to several orders of magnitude faster than repeated `INSERT INTO ... VALUES (...)`, which are usually not portable. These should be employed in `dbWriteTable()`, perhaps with an argument `fast = TRUE` and a fallback to `INSERT INTO`.

Related: https://github.com/hadley/dplyr/issues/1471.

**Comment by beanumber** [comment]
+1 

Support for `LOAD DATA INFILE ...` in MySQL would be sweet! Note that this would obviate the need to read the data into R so you would specify a CSV to import from rather than a data.frame to write, right?

**Comment by krlmlr** [comment]
This is about using fast import for dbWriteTable(). I fear that the input data formats are too different to attempt a standardization. On the other hand, the required input format could be documented with the corresponding DBI backend.

What are the differences for the input formats for, say, MySQL, Postgres and SQLite?

**Comment by hannesmuehleisen** [comment]
RSQLite and MonetDBLite support a file name as the `value=` argument to `dbWriteTable`, which invokes the bulk CSV loader. I think this behavior could be standardized.

**Comment by krlmlr** [comment]
@hannesmuehleisen: Thanks for chiming in. I'm wondering if the CSV syntax is standard as well. It seems that delimiters usually can be specified; what about quoting, embedded newlines, other funny CSV stuff?

Also, I remember some DBMS require a path that is accessible by the server, e.g., Postgres had a special syntax to bulk-load from the client.

**Comment by hannesmuehleisen** [comment]
CSVs are incredibly messy. There are some attempts at standardisation, but in practise literally anything could appear. 

The paths in my examples all need to be accessible from server indeed. So this only makes sense from localhost and even then there might be a SSH tunnel that goes to a remote box. Its not pretty in general.

**Comment by krlmlr** [comment]
I think these two points reduce the usefulness of a standardized interface. After all, you can always bulk-load by hand via `dbGetQuery(con, "LOAD DATA INFILE ...")` or whatever. On the other hand, `dbWriteTable()` for data frames is in full control and can craft a CSV file that will be digestible by the server (and possibly also find a way to transfer it from the client).

**Comment by cronacronis** [comment]
Should we consider `bulk_load` verb? Whether we can store implementations for every engine?
(PostgreSQL `COPY`)[http://www.postgresql.org/docs/current/static/sql-copy.html]

**Comment by hadley** [comment]
Why shouldn't `dbWriteTable()` be fast by default?  It seems to me that this is the responsibility of the individual backend author. DBI can provide a default ANSI SQL insert based implementation, and individual authors can implement faster approaches where available.

**Comment by krlmlr** [comment]
Fastest import speeds are usually achieved with some sort of CSV file to which the database server has access somehow. This is not standardized, though. I thought about this type of import when filing this issue.

If the data are already in R, I agree that DBI backends can make use of "their" fastest import and write a CSV if necessary.

**Comment by momeara** [comment]
On @eddelbuettel's suggestion, I contacted Tomoaki, the maintainer of RPostgreSQL about this issue, but I did not get a response.

**Comment by krlmlr** [comment]
The new [_arkdb_ package](https://github.com/cboettig/arkdb) implements database-agnostic chunked CSV import and export. I don't think we can usefully standardize bulk import/export in _DBI_, but we could write better documentation that shows how to get large datasets into and out of a database.
