### ISSUE TITLE
Think about server-side execution of R code

### ISSUE THREAD

**Issue by krlmlr** [r-dbi/DBI#73]
How could a standard interface for allowing execution of arbitrary R code on the database server look like? Of course, this requires facilities for server-side execution of R code, similar to PL/R and EXASOL.

@marcelboldt: How would this work in EXASOL? Can you sketch the interface?

**Comment by krlmlr** [comment]
@hannesmuehleisen: Seems to be relevant for MonetDB, too?

**Comment by hannesmuehleisen** [comment]
We have that functionality in MonetDB.R with `mdbapply`. Here is an example:

    dbWriteTable(conn, "mtcars", mtcars)
    mpgplus42 <- mdbapply(conn, "mtcars", "double", function(d) {
        d$mpg + 42
    })

This will ship the function to MonetDB, and run it on the table. The second parameter ("mtcars") can also be a full SQL query, in which case the function is run on the query result. The parameter passed to the function (`d`) is a `data.frame` like the one you would get by calling `dbGetQuery()`. Global variables  used in that function are automatically detected (using `codetools::findGlobals) and also shipped to the DB.

I believe this to be a reasonably generic API.

**Comment by krlmlr** [comment]
- What are the "R in DB" systems, what is their interface?
    - PL/R (CC @jconway)
    - MonetDB
    - EXASOL
    - SQL Server (CC @andrie)
    - ...?

**Comment by hannesmuehleisen** [comment]
Here is the interface for MonetDB: https://www.monetdb.org/content/embedded-r-monetdb

**Comment by krlmlr** [comment]
This would be nice to have, but currently feels out of scope for DBI.
