### ISSUE TITLE
dbCanConnect ?

### ISSUE THREAD

**Issue by hadley** [r-dbi/DBI#87]
It might be useful to have a function that allows you to determine if a set of connection parameters is valid, without actually generating the connection

**Comment by krlmlr** [comment]
With default implementation:

```
tryCatch({dbConnect(...); TRUE}; error = function(e) FALSE)
```

**Comment by hadley** [comment]
Default would also need a `dbDisconnect()` in case of success.

**Comment by chasemc** [comment]
Maybe it's something on my end but if the path is set to a non-database dbCanConnect is still returning true:
```r
DBI::dbCanConnect(drv = RSQLite::SQLite(),
                  dbname = base::file.path(filePath, "server.r")) 


[1] TRUE
Warning message:
Couldn't set synchronous mode: file is not a database
Use `synchronous` = NULL to turn off this warning. 
```
